// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Peent.Persistence;

namespace Peent.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190813183308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Peent.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrencyId");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("WorkspaceId");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Peent.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Peent.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("WorkspaceId");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Peent.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<int>("DecimalPlaces")
                        .HasMaxLength(18);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Peent.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<long?>("TransactionId");

                    b.Property<int>("WorkspaceId");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Peent.Domain.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<short>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Peent.Domain.Entities.TransactionEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(38,18)");

                    b.Property<int>("CurrencyId");

                    b.Property<decimal?>("ForeignAmount")
                        .HasColumnType("decimal(38,18)");

                    b.Property<int>("ForeignCurrencyId");

                    b.Property<long>("TransactionId");

                    b.Property<long?>("TransactionId1");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ForeignCurrencyId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("TransactionId1");

                    b.ToTable("TransactionEntries");
                });

            modelBuilder.Entity("Peent.Domain.Entities.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Peent.Domain.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Peent.Domain.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Peent.Domain.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Peent.Domain.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Peent.Domain.Entities.Account", b =>
                {
                    b.HasOne("Peent.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Peent.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Peent.Domain.ValueObjects.CreationInfo", "CreationInfo", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnName("CreatedById");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnName("CreationDate");

                            b1.HasKey("AccountId");

                            b1.HasIndex("CreatedById");

                            b1.ToTable("Accounts");

                            b1.HasOne("Peent.Domain.Entities.Account")
                                .WithOne("CreationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.CreationInfo", "AccountId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "CreatedBy")
                                .WithMany()
                                .HasForeignKey("CreatedById")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.DeletionInfo", "DeletionInfo", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("DeletedById")
                                .HasColumnName("DeletedById");

                            b1.Property<DateTime?>("DeletionDate")
                                .HasColumnName("DeletionDate");

                            b1.HasKey("AccountId");

                            b1.HasIndex("DeletedById");

                            b1.ToTable("Accounts");

                            b1.HasOne("Peent.Domain.Entities.Account")
                                .WithOne("DeletionInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.DeletionInfo", "AccountId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "DeletedBy")
                                .WithMany()
                                .HasForeignKey("DeletedById")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.ModificationInfo", "ModificationInfo", b1 =>
                        {
                            b1.Property<int>("AccountId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime?>("LastModificationDate")
                                .HasColumnName("LastModificationDate");

                            b1.Property<string>("LastModifiedById")
                                .HasColumnName("LastModifiedById");

                            b1.HasKey("AccountId");

                            b1.HasIndex("LastModifiedById");

                            b1.ToTable("Accounts");

                            b1.HasOne("Peent.Domain.Entities.Account")
                                .WithOne("ModificationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.ModificationInfo", "AccountId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "LastModifiedBy")
                                .WithMany()
                                .HasForeignKey("LastModifiedById")
                                .OnDelete(DeleteBehavior.Restrict);
                        });
                });

            modelBuilder.Entity("Peent.Domain.Entities.Category", b =>
                {
                    b.HasOne("Peent.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Peent.Domain.ValueObjects.CreationInfo", "CreationInfo", b1 =>
                        {
                            b1.Property<int>("CategoryId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnName("CreatedById");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnName("CreationDate");

                            b1.HasKey("CategoryId");

                            b1.HasIndex("CreatedById");

                            b1.ToTable("Categories");

                            b1.HasOne("Peent.Domain.Entities.Category")
                                .WithOne("CreationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.CreationInfo", "CategoryId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "CreatedBy")
                                .WithMany()
                                .HasForeignKey("CreatedById")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.DeletionInfo", "DeletionInfo", b1 =>
                        {
                            b1.Property<int>("CategoryId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("DeletedById")
                                .HasColumnName("DeletedById");

                            b1.Property<DateTime?>("DeletionDate")
                                .HasColumnName("DeletionDate");

                            b1.HasKey("CategoryId");

                            b1.HasIndex("DeletedById");

                            b1.ToTable("Categories");

                            b1.HasOne("Peent.Domain.Entities.Category")
                                .WithOne("DeletionInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.DeletionInfo", "CategoryId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "DeletedBy")
                                .WithMany()
                                .HasForeignKey("DeletedById")
                                .OnDelete(DeleteBehavior.Restrict);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.ModificationInfo", "ModificationInfo", b1 =>
                        {
                            b1.Property<int>("CategoryId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime?>("LastModificationDate")
                                .HasColumnName("LastModificationDate");

                            b1.Property<string>("LastModifiedById")
                                .HasColumnName("LastModifiedById");

                            b1.HasKey("CategoryId");

                            b1.HasIndex("LastModifiedById");

                            b1.ToTable("Categories");

                            b1.HasOne("Peent.Domain.Entities.Category")
                                .WithOne("ModificationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.ModificationInfo", "CategoryId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "LastModifiedBy")
                                .WithMany()
                                .HasForeignKey("LastModifiedById")
                                .OnDelete(DeleteBehavior.Restrict);
                        });
                });

            modelBuilder.Entity("Peent.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Peent.Domain.Entities.Transaction")
                        .WithMany("Tags")
                        .HasForeignKey("TransactionId");

                    b.HasOne("Peent.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Peent.Domain.ValueObjects.CreationInfo", "CreationInfo", b1 =>
                        {
                            b1.Property<int>("TagId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnName("CreatedById");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnName("CreationDate");

                            b1.HasKey("TagId");

                            b1.HasIndex("CreatedById");

                            b1.ToTable("Tags");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "CreatedBy")
                                .WithMany()
                                .HasForeignKey("CreatedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.Tag")
                                .WithOne("CreationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.CreationInfo", "TagId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.DeletionInfo", "DeletionInfo", b1 =>
                        {
                            b1.Property<int>("TagId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("DeletedById")
                                .HasColumnName("DeletedById");

                            b1.Property<DateTime?>("DeletionDate")
                                .HasColumnName("DeletionDate");

                            b1.HasKey("TagId");

                            b1.HasIndex("DeletedById");

                            b1.ToTable("Tags");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "DeletedBy")
                                .WithMany()
                                .HasForeignKey("DeletedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.Tag")
                                .WithOne("DeletionInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.DeletionInfo", "TagId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.ModificationInfo", "ModificationInfo", b1 =>
                        {
                            b1.Property<int>("TagId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime?>("LastModificationDate")
                                .HasColumnName("LastModificationDate");

                            b1.Property<string>("LastModifiedById")
                                .HasColumnName("LastModifiedById");

                            b1.HasKey("TagId");

                            b1.HasIndex("LastModifiedById");

                            b1.ToTable("Tags");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "LastModifiedBy")
                                .WithMany()
                                .HasForeignKey("LastModifiedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.Tag")
                                .WithOne("ModificationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.ModificationInfo", "TagId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Peent.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Peent.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Peent.Domain.ValueObjects.CreationInfo", "CreationInfo", b1 =>
                        {
                            b1.Property<long>("TransactionId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnName("CreatedById");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnName("CreationDate");

                            b1.HasKey("TransactionId");

                            b1.HasIndex("CreatedById");

                            b1.ToTable("Transactions");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "CreatedBy")
                                .WithMany()
                                .HasForeignKey("CreatedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.Transaction")
                                .WithOne("CreationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.CreationInfo", "TransactionId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.DeletionInfo", "DeletionInfo", b1 =>
                        {
                            b1.Property<long>("TransactionId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("DeletedById")
                                .HasColumnName("DeletedById");

                            b1.Property<DateTime?>("DeletionDate")
                                .HasColumnName("DeletionDate");

                            b1.HasKey("TransactionId");

                            b1.HasIndex("DeletedById");

                            b1.ToTable("Transactions");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "DeletedBy")
                                .WithMany()
                                .HasForeignKey("DeletedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.Transaction")
                                .WithOne("DeletionInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.DeletionInfo", "TransactionId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.ModificationInfo", "ModificationInfo", b1 =>
                        {
                            b1.Property<long>("TransactionId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime?>("LastModificationDate")
                                .HasColumnName("LastModificationDate");

                            b1.Property<string>("LastModifiedById")
                                .HasColumnName("LastModifiedById");

                            b1.HasKey("TransactionId");

                            b1.HasIndex("LastModifiedById");

                            b1.ToTable("Transactions");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "LastModifiedBy")
                                .WithMany()
                                .HasForeignKey("LastModifiedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.Transaction")
                                .WithOne("ModificationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.ModificationInfo", "TransactionId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Peent.Domain.Entities.TransactionEntry", b =>
                {
                    b.HasOne("Peent.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Peent.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Peent.Domain.Entities.Currency", "ForeignCurrency")
                        .WithMany()
                        .HasForeignKey("ForeignCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Peent.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Peent.Domain.Entities.Transaction")
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId1");

                    b.OwnsOne("Peent.Domain.ValueObjects.CreationInfo", "CreationInfo", b1 =>
                        {
                            b1.Property<long>("TransactionEntryId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnName("CreatedById");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnName("CreationDate");

                            b1.HasKey("TransactionEntryId");

                            b1.HasIndex("CreatedById");

                            b1.ToTable("TransactionEntries");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "CreatedBy")
                                .WithMany()
                                .HasForeignKey("CreatedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.TransactionEntry")
                                .WithOne("CreationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.CreationInfo", "TransactionEntryId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.DeletionInfo", "DeletionInfo", b1 =>
                        {
                            b1.Property<long>("TransactionEntryId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("DeletedById")
                                .HasColumnName("DeletedById");

                            b1.Property<DateTime?>("DeletionDate")
                                .HasColumnName("DeletionDate");

                            b1.HasKey("TransactionEntryId");

                            b1.HasIndex("DeletedById");

                            b1.ToTable("TransactionEntries");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "DeletedBy")
                                .WithMany()
                                .HasForeignKey("DeletedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.TransactionEntry")
                                .WithOne("DeletionInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.DeletionInfo", "TransactionEntryId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.ModificationInfo", "ModificationInfo", b1 =>
                        {
                            b1.Property<long>("TransactionEntryId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime?>("LastModificationDate")
                                .HasColumnName("LastModificationDate");

                            b1.Property<string>("LastModifiedById")
                                .HasColumnName("LastModifiedById");

                            b1.HasKey("TransactionEntryId");

                            b1.HasIndex("LastModifiedById");

                            b1.ToTable("TransactionEntries");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "LastModifiedBy")
                                .WithMany()
                                .HasForeignKey("LastModifiedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.TransactionEntry")
                                .WithOne("ModificationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.ModificationInfo", "TransactionEntryId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Peent.Domain.Entities.Workspace", b =>
                {
                    b.OwnsOne("Peent.Domain.ValueObjects.CreationInfo", "CreationInfo", b1 =>
                        {
                            b1.Property<int>("WorkspaceId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnName("CreatedById");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnName("CreationDate");

                            b1.HasKey("WorkspaceId");

                            b1.HasIndex("CreatedById");

                            b1.ToTable("Workspaces");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "CreatedBy")
                                .WithMany()
                                .HasForeignKey("CreatedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.Workspace")
                                .WithOne("CreationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.CreationInfo", "WorkspaceId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.DeletionInfo", "DeletionInfo", b1 =>
                        {
                            b1.Property<int>("WorkspaceId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("DeletedById")
                                .HasColumnName("DeletedById");

                            b1.Property<DateTime?>("DeletionDate")
                                .HasColumnName("DeletionDate");

                            b1.HasKey("WorkspaceId");

                            b1.HasIndex("DeletedById");

                            b1.ToTable("Workspaces");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "DeletedBy")
                                .WithMany()
                                .HasForeignKey("DeletedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.Workspace")
                                .WithOne("DeletionInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.DeletionInfo", "WorkspaceId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Peent.Domain.ValueObjects.ModificationInfo", "ModificationInfo", b1 =>
                        {
                            b1.Property<int>("WorkspaceId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime?>("LastModificationDate")
                                .HasColumnName("LastModificationDate");

                            b1.Property<string>("LastModifiedById")
                                .HasColumnName("LastModifiedById");

                            b1.HasKey("WorkspaceId");

                            b1.HasIndex("LastModifiedById");

                            b1.ToTable("Workspaces");

                            b1.HasOne("Peent.Domain.Entities.ApplicationUser", "LastModifiedBy")
                                .WithMany()
                                .HasForeignKey("LastModifiedById")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.HasOne("Peent.Domain.Entities.Workspace")
                                .WithOne("ModificationInfo")
                                .HasForeignKey("Peent.Domain.ValueObjects.ModificationInfo", "WorkspaceId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
